import { useState } from "react";
import { toast } from "sonner";
import { ChevronDown, ChevronRight, Plus, Pencil, Trash2, ArrowUp, ArrowDown } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";

export default function WorkflowTemplates() {
  const utils = trpc.useUtils();
  const { data: templates } = trpc.workflow.templates.list.useQuery();
  const [expandedId, setExpandedId] = useState<number | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);

  const deleteTemplate = trpc.workflow.templates.delete.useMutation({
    onSuccess: () => {
      toast.success("已删除");
      utils.workflow.templates.list.invalidate();
    },
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">SOP 模板配置</h1>
          <p className="text-sm text-muted-foreground">配置权益验收工作流模板与步骤</p>
        </div>
        <Button onClick={() => setDialogOpen(true)}>
          <Plus className="mr-1 h-4 w-4" />
          新增模板
        </Button>
      </div>

      <div className="space-y-3">
        {templates?.map((t) => (
          <Card key={t.id}>
            <button
              className="flex w-full items-center gap-3 p-4 text-left"
              onClick={() => setExpandedId(expandedId === t.id ? null : t.id)}
            >
              {expandedId === t.id ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <span className="font-medium">{t.name}</span>
                  {t.autoGenerateDaysBefore != null && (
                    <Badge variant="outline">比赛前 {t.autoGenerateDaysBefore} 天自动生成</Badge>
                  )}
                  {!t.isActive && <Badge variant="secondary">已停用</Badge>}
                </div>
                {t.description && <p className="text-sm text-muted-foreground">{t.description}</p>}
              </div>
              <Button
                size="icon"
                variant="ghost"
                onClick={(e) => {
                  e.stopPropagation();
                  if (confirm(`确认删除模板「${t.name}」？`)) deleteTemplate.mutate({ id: t.id });
                }}
              >
                <Trash2 className="h-4 w-4 text-destructive" />
              </Button>
            </button>
            {expandedId === t.id && (
              <CardContent className="border-t pt-4">
                <StepsManager templateId={t.id} />
              </CardContent>
            )}
          </Card>
        ))}
        {templates?.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">暂无 SOP 模板</p>}
      </div>

      <TemplateDialog
        open={dialogOpen}
        onClose={() => setDialogOpen(false)}
        onSaved={() => {
          setDialogOpen(false);
          utils.workflow.templates.list.invalidate();
        }}
      />
    </div>
  );
}

function TemplateDialog({
  open,
  onClose,
  onSaved,
}: {
  open: boolean;
  onClose: () => void;
  onSaved: () => void;
}) {
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [autoGenerateDaysBefore, setAutoGenerateDaysBefore] = useState("");

  const create = trpc.workflow.templates.create.useMutation({
    onSuccess: () => {
      setName("");
      setDescription("");
      setAutoGenerateDaysBefore("");
      onSaved();
    },
    onError: (e) => toast.error(e.message),
  });

  return (
    <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>新增 SOP 模板</DialogTitle>
        </DialogHeader>
        <div className="space-y-3">
          <div className="space-y-1.5">
            <Label>模板名称</Label>
            <Input value={name} onChange={(e) => setName(e.target.value)} />
          </div>
          <div className="space-y-1.5">
            <Label>描述</Label>
            <Textarea value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
          <div className="space-y-1.5">
            <Label>自动生成规则（比赛前 N 天，留空则不自动生成）</Label>
            <Input
              type="number"
              value={autoGenerateDaysBefore}
              onChange={(e) => setAutoGenerateDaysBefore(e.target.value)}
              placeholder="例如 7"
            />
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={onClose}>
            取消
          </Button>
          <Button
            onClick={() => {
              if (!name) {
                toast.error("请填写模板名称");
                return;
              }
              create.mutate({
                name,
                description: description || undefined,
                autoGenerateDaysBefore: autoGenerateDaysBefore ? Number(autoGenerateDaysBefore) : undefined,
              });
            }}
            disabled={create.isPending}
          >
            创建
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function StepsManager({ templateId }: { templateId: number }) {
  const utils = trpc.useUtils();
  const { data } = trpc.workflow.templates.get.useQuery({ id: templateId });
  const { data: users } = trpc.userManagement.list.useQuery();
  const [dialogStep, setDialogStep] = useState<NonNullable<typeof data>["steps"][number] | "new" | null>(null);

  const deleteStep = trpc.workflow.steps.delete.useMutation({
    onSuccess: () => {
      toast.success("已删除");
      utils.workflow.templates.get.invalidate({ id: templateId });
    },
  });
  const updateStep = trpc.workflow.steps.update.useMutation({
    onSuccess: () => utils.workflow.templates.get.invalidate({ id: templateId }),
  });

  const steps = data?.steps ?? [];

  function moveStep(index: number, direction: -1 | 1) {
    const target = steps[index + direction];
    const current = steps[index];
    if (!target) return;
    updateStep.mutate({ id: current.id, stepOrder: target.stepOrder });
    updateStep.mutate({ id: target.id, stepOrder: current.stepOrder });
  }

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-medium">步骤</h3>
        <Button size="sm" onClick={() => setDialogStep("new")}>
          <Plus className="mr-1 h-3 w-3" />
          新增步骤
        </Button>
      </div>
      <div className="space-y-2">
        {steps.map((step, idx) => {
          const assignee = users?.find((u) => u.id === step.defaultAssigneeId);
          return (
            <div key={step.id} className="flex items-center gap-3 rounded-md border p-2 text-sm">
              <span className="w-6 text-center text-muted-foreground">{step.stepOrder}</span>
              <div className="flex-1">
                <div className="font-medium">{step.name}</div>
                <div className="text-xs text-muted-foreground">
                  {step.dueDayOffset < 0 ? `比赛前 ${-step.dueDayOffset} 天` : `比赛后 ${step.dueDayOffset} 天`}
                  {step.requiresFile && " · 需要文件"}
                  {step.requiresNote && " · 需要备注"}
                  {assignee && ` · 默认负责人：${assignee.name}`}
                </div>
              </div>
              <Button size="icon" variant="ghost" disabled={idx === 0} onClick={() => moveStep(idx, -1)}>
                <ArrowUp className="h-3.5 w-3.5" />
              </Button>
              <Button
                size="icon"
                variant="ghost"
                disabled={idx === steps.length - 1}
                onClick={() => moveStep(idx, 1)}
              >
                <ArrowDown className="h-3.5 w-3.5" />
              </Button>
              <Button size="icon" variant="ghost" onClick={() => setDialogStep(step)}>
                <Pencil className="h-3.5 w-3.5" />
              </Button>
              <Button size="icon" variant="ghost" onClick={() => deleteStep.mutate({ id: step.id })}>
                <Trash2 className="h-3.5 w-3.5 text-destructive" />
              </Button>
            </div>
          );
        })}
        {steps.length === 0 && <p className="text-sm text-muted-foreground">暂无步骤</p>}
      </div>

      <StepDialog
        templateId={templateId}
        step={dialogStep}
        nextOrder={steps.length + 1}
        onClose={() => setDialogStep(null)}
        onSaved={() => {
          setDialogStep(null);
          utils.workflow.templates.get.invalidate({ id: templateId });
        }}
      />
    </div>
  );
}

function StepDialog({
  templateId,
  step,
  nextOrder,
  onClose,
  onSaved,
}: {
  templateId: number;
  step:
    | {
        id: number;
        name: string;
        description: string | null;
        dueDayOffset: number;
        requiresFile: boolean;
        requiresNote: boolean;
        defaultAssigneeId: number | null;
      }
    | "new"
    | null;
  nextOrder: number;
  onClose: () => void;
  onSaved: () => void;
}) {
  const isNew = step === "new";
  const existing = isNew ? null : step;
  const { data: users } = trpc.userManagement.list.useQuery();

  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [dueDayOffset, setDueDayOffset] = useState("-1");
  const [requiresFile, setRequiresFile] = useState(false);
  const [requiresNote, setRequiresNote] = useState(false);
  const [defaultAssigneeId, setDefaultAssigneeId] = useState<string>("");

  const create = trpc.workflow.steps.create.useMutation({ onSuccess: onSaved, onError: (e) => toast.error(e.message) });
  const update = trpc.workflow.steps.update.useMutation({ onSuccess: onSaved, onError: (e) => toast.error(e.message) });

  function reset(s: typeof existing) {
    setName(s?.name ?? "");
    setDescription(s?.description ?? "");
    setDueDayOffset(s ? String(s.dueDayOffset) : "-1");
    setRequiresFile(s?.requiresFile ?? false);
    setRequiresNote(s?.requiresNote ?? false);
    setDefaultAssigneeId(s?.defaultAssigneeId != null ? String(s.defaultAssigneeId) : "");
  }

  return (
    <Dialog
      open={step !== null}
      onOpenChange={(open) => {
        if (open) reset(existing);
        else onClose();
      }}
    >
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{isNew ? "新增步骤" : "编辑步骤"}</DialogTitle>
        </DialogHeader>
        <div className="space-y-3">
          <div className="space-y-1.5">
            <Label>步骤名称</Label>
            <Input value={name} onChange={(e) => setName(e.target.value)} />
          </div>
          <div className="space-y-1.5">
            <Label>说明</Label>
            <Textarea value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
          <div className="space-y-1.5">
            <Label>截止日期偏移（负数=比赛前N天，正数=比赛后N天）</Label>
            <Input type="number" value={dueDayOffset} onChange={(e) => setDueDayOffset(e.target.value)} />
          </div>
          <div className="flex items-center gap-4">
            <label className="flex items-center gap-2 text-sm">
              <Checkbox checked={requiresFile} onCheckedChange={(v) => setRequiresFile(!!v)} />
              需要文件
            </label>
            <label className="flex items-center gap-2 text-sm">
              <Checkbox checked={requiresNote} onCheckedChange={(v) => setRequiresNote(!!v)} />
              需要备注
            </label>
          </div>
          <div className="space-y-1.5">
            <Label>默认负责人</Label>
            <Select value={defaultAssigneeId} onValueChange={setDefaultAssigneeId}>
              <SelectTrigger>
                <SelectValue placeholder="选择负责人（可选）" />
              </SelectTrigger>
              <SelectContent>
                {users?.map((u) => (
                  <SelectItem key={u.id} value={String(u.id)}>
                    {u.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={onClose}>
            取消
          </Button>
          <Button
            onClick={() => {
              if (!name) {
                toast.error("请填写步骤名称");
                return;
              }
              const payload = {
                name,
                description: description || undefined,
                dueDayOffset: Number(dueDayOffset),
                requiresFile,
                requiresNote,
                defaultAssigneeId: defaultAssigneeId ? Number(defaultAssigneeId) : undefined,
              };
              if (isNew) {
                create.mutate({ templateId, stepOrder: nextOrder, ...payload });
              } else if (existing) {
                update.mutate({ id: existing.id, ...payload });
              }
            }}
            disabled={create.isPending || update.isPending}
          >
            保存
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
