import { and, asc, eq } from "drizzle-orm";
import { db } from "../db";
import { matches, sopSteps, sopTemplates, workflowInstances, workflowStepExecutions } from "../db/schema";

function startOfDay(date: Date): Date {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  return d;
}

export async function autoGenerateWorkflows() {
  const templates = await db
    .select()
    .from(sopTemplates)
    .where(eq(sopTemplates.isActive, true));
  const eligibleTemplates = templates.filter((t) => t.autoGenerateDaysBefore != null);

  const today = startOfDay(new Date());

  for (const template of eligibleTemplates) {
    const clubMatches = await db.select().from(matches).where(eq(matches.clubId, template.clubId));

    for (const match of clubMatches) {
      const matchDay = startOfDay(match.matchDate);
      const diffDays = Math.round((matchDay.getTime() - today.getTime()) / 86_400_000);
      if (diffDays !== template.autoGenerateDaysBefore) continue;

      const [existing] = await db
        .select()
        .from(workflowInstances)
        .where(
          and(
            eq(workflowInstances.templateId, template.id),
            eq(workflowInstances.matchId, match.id),
          ),
        )
        .limit(1);
      if (existing) continue;

      const steps = await db
        .select()
        .from(sopSteps)
        .where(eq(sopSteps.templateId, template.id))
        .orderBy(asc(sopSteps.stepOrder));

      const [result] = await db.insert(workflowInstances).values({
        clubId: template.clubId,
        templateId: template.id,
        matchId: match.id,
      });
      const instanceId = result.insertId;

      for (const step of steps) {
        const dueDate = new Date(match.matchDate);
        dueDate.setDate(dueDate.getDate() + step.dueDayOffset);
        await db.insert(workflowStepExecutions).values({
          clubId: template.clubId,
          instanceId,
          stepId: step.id,
          stepOrder: step.stepOrder,
          assigneeId: step.defaultAssigneeId ?? null,
          status: "active",
          dueDate,
        });
      }

      console.log(
        `[cron] Generated workflow instance for template "${template.name}" / match #${match.id}`,
      );
    }
  }
}

const ONE_DAY_MS = 24 * 60 * 60 * 1000;

export function startHeartbeat() {
  autoGenerateWorkflows().catch((err) => console.error("[cron] autoGenerateWorkflows failed", err));
  setInterval(() => {
    autoGenerateWorkflows().catch((err) => console.error("[cron] autoGenerateWorkflows failed", err));
  }, ONE_DAY_MS);
}
