import { z } from "zod";
import { and, asc, eq, inArray } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { router, protectedProcedure, adminProcedure } from "../trpc";
import { db } from "../../db";
import {
  matches,
  sopSteps,
  sopTemplates,
  workflowInstances,
  workflowStepExecutions,
} from "../../db/schema";

async function assertTemplateInClub(templateId: number, clubId: number) {
  const [template] = await db
    .select()
    .from(sopTemplates)
    .where(and(eq(sopTemplates.id, templateId), eq(sopTemplates.clubId, clubId)))
    .limit(1);
  if (!template) throw new TRPCError({ code: "NOT_FOUND", message: "SOP 模板不存在" });
  return template;
}

async function assertStepInClub(stepId: number, clubId: number) {
  const [step] = await db.select().from(sopSteps).where(eq(sopSteps.id, stepId)).limit(1);
  if (!step) throw new TRPCError({ code: "NOT_FOUND", message: "步骤不存在" });
  await assertTemplateInClub(step.templateId, clubId);
  return step;
}

async function assertMatchInClub(matchId: number, clubId: number) {
  const [match] = await db
    .select()
    .from(matches)
    .where(and(eq(matches.id, matchId), eq(matches.clubId, clubId)))
    .limit(1);
  if (!match) throw new TRPCError({ code: "NOT_FOUND", message: "比赛不存在" });
  return match;
}

const templatesRouter = router({
  list: protectedProcedure.query(async ({ ctx }) => {
    if (!ctx.user.clubId) return [];
    return db.select().from(sopTemplates).where(eq(sopTemplates.clubId, ctx.user.clubId));
  }),

  get: protectedProcedure.input(z.object({ id: z.number() })).query(async ({ ctx, input }) => {
    const template = await assertTemplateInClub(input.id, ctx.user.clubId!);
    const steps = await db
      .select()
      .from(sopSteps)
      .where(eq(sopSteps.templateId, input.id))
      .orderBy(asc(sopSteps.stepOrder));
    return { template, steps };
  }),

  create: adminProcedure
    .input(
      z.object({
        name: z.string().min(1),
        description: z.string().optional(),
        autoGenerateDaysBefore: z.number().optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const [result] = await db.insert(sopTemplates).values({
        clubId: ctx.user.clubId!,
        name: input.name,
        description: input.description,
        autoGenerateDaysBefore: input.autoGenerateDaysBefore,
        createdBy: ctx.user.id,
      });
      const [template] = await db.select().from(sopTemplates).where(eq(sopTemplates.id, result.insertId)).limit(1);
      return template;
    }),

  update: adminProcedure
    .input(
      z.object({
        id: z.number(),
        name: z.string().optional(),
        description: z.string().optional(),
        isActive: z.boolean().optional(),
        autoGenerateDaysBefore: z.number().nullable().optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const { id, ...rest } = input;
      await assertTemplateInClub(id, ctx.user.clubId!);
      await db.update(sopTemplates).set(rest).where(eq(sopTemplates.id, id));
      const [template] = await db.select().from(sopTemplates).where(eq(sopTemplates.id, id)).limit(1);
      return template;
    }),

  delete: adminProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ ctx, input }) => {
      await assertTemplateInClub(input.id, ctx.user.clubId!);
      await db.delete(sopSteps).where(eq(sopSteps.templateId, input.id));
      await db.delete(sopTemplates).where(eq(sopTemplates.id, input.id));
      return { success: true };
    }),
});

const stepsRouter = router({
  create: adminProcedure
    .input(
      z.object({
        templateId: z.number(),
        stepOrder: z.number(),
        name: z.string().min(1),
        description: z.string().optional(),
        dueDayOffset: z.number().default(-1),
        requiresFile: z.boolean().default(false),
        requiresNote: z.boolean().default(false),
        defaultAssigneeId: z.number().optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      await assertTemplateInClub(input.templateId, ctx.user.clubId!);
      const [result] = await db.insert(sopSteps).values(input);
      const [step] = await db.select().from(sopSteps).where(eq(sopSteps.id, result.insertId)).limit(1);
      return step;
    }),

  update: adminProcedure
    .input(
      z.object({
        id: z.number(),
        stepOrder: z.number().optional(),
        name: z.string().optional(),
        description: z.string().optional(),
        dueDayOffset: z.number().optional(),
        requiresFile: z.boolean().optional(),
        requiresNote: z.boolean().optional(),
        defaultAssigneeId: z.number().nullable().optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const { id, ...rest } = input;
      await assertStepInClub(id, ctx.user.clubId!);
      await db.update(sopSteps).set(rest).where(eq(sopSteps.id, id));
      const [step] = await db.select().from(sopSteps).where(eq(sopSteps.id, id)).limit(1);
      return step;
    }),

  delete: adminProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ ctx, input }) => {
      await assertStepInClub(input.id, ctx.user.clubId!);
      await db.delete(sopSteps).where(eq(sopSteps.id, input.id));
      return { success: true };
    }),
});

const instancesRouter = router({
  byMatch: protectedProcedure
    .input(z.object({ matchId: z.number() }))
    .query(async ({ ctx, input }) => {
      await assertMatchInClub(input.matchId, ctx.user.clubId!);
      const instances = await db
        .select()
        .from(workflowInstances)
        .where(and(eq(workflowInstances.matchId, input.matchId), eq(workflowInstances.clubId, ctx.user.clubId!)));

      return Promise.all(
        instances.map(async (instance) => {
          const [template] = await db
            .select()
            .from(sopTemplates)
            .where(eq(sopTemplates.id, instance.templateId))
            .limit(1);
          const executions = await db
            .select()
            .from(workflowStepExecutions)
            .where(eq(workflowStepExecutions.instanceId, instance.id))
            .orderBy(asc(workflowStepExecutions.stepOrder));
          return { instance, template, executions };
        }),
      );
    }),

  all: adminProcedure.query(async ({ ctx }) => {
    const instances = await db
      .select()
      .from(workflowInstances)
      .where(eq(workflowInstances.clubId, ctx.user.clubId!));

    return Promise.all(
      instances.map(async (instance) => {
        const [template] = await db
          .select()
          .from(sopTemplates)
          .where(eq(sopTemplates.id, instance.templateId))
          .limit(1);
        const [match] = await db.select().from(matches).where(eq(matches.id, instance.matchId)).limit(1);
        const executions = await db
          .select()
          .from(workflowStepExecutions)
          .where(eq(workflowStepExecutions.instanceId, instance.id))
          .orderBy(asc(workflowStepExecutions.stepOrder));
        return { instance, template, match, executions };
      }),
    );
  }),

  generate: adminProcedure
    .input(
      z.object({
        matchId: z.number(),
        templateId: z.number(),
        assigneeOverrides: z.record(z.string(), z.number()).optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const clubId = ctx.user.clubId!;
      const match = await assertMatchInClub(input.matchId, clubId);
      await assertTemplateInClub(input.templateId, clubId);

      const steps = await db
        .select()
        .from(sopSteps)
        .where(eq(sopSteps.templateId, input.templateId))
        .orderBy(asc(sopSteps.stepOrder));

      const [result] = await db.insert(workflowInstances).values({
        clubId,
        templateId: input.templateId,
        matchId: input.matchId,
      });
      const instanceId = result.insertId;

      for (const step of steps) {
        const overrideAssignee = input.assigneeOverrides?.[String(step.id)];
        const dueDate = new Date(match.matchDate);
        dueDate.setDate(dueDate.getDate() + step.dueDayOffset);
        await db.insert(workflowStepExecutions).values({
          clubId,
          instanceId,
          stepId: step.id,
          stepOrder: step.stepOrder,
          assigneeId: overrideAssignee ?? step.defaultAssigneeId ?? null,
          status: "active",
          dueDate,
        });
      }

      const [instance] = await db
        .select()
        .from(workflowInstances)
        .where(eq(workflowInstances.id, instanceId))
        .limit(1);
      return instance;
    }),

  delete: adminProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ ctx, input }) => {
      const [instance] = await db
        .select()
        .from(workflowInstances)
        .where(and(eq(workflowInstances.id, input.id), eq(workflowInstances.clubId, ctx.user.clubId!)))
        .limit(1);
      if (!instance) throw new TRPCError({ code: "NOT_FOUND" });
      await db.delete(workflowStepExecutions).where(eq(workflowStepExecutions.instanceId, input.id));
      await db.delete(workflowInstances).where(eq(workflowInstances.id, input.id));
      return { success: true };
    }),
});

const executeRouter = router({
  myTasks: protectedProcedure.query(async ({ ctx }) => {
    const executions = await db
      .select()
      .from(workflowStepExecutions)
      .where(
        and(
          eq(workflowStepExecutions.clubId, ctx.user.clubId!),
          eq(workflowStepExecutions.assigneeId, ctx.user.id),
        ),
      );

    return enrichExecutions(executions);
  }),

  allTasks: adminProcedure.query(async ({ ctx }) => {
    const executions = await db
      .select()
      .from(workflowStepExecutions)
      .where(eq(workflowStepExecutions.clubId, ctx.user.clubId!));

    return enrichExecutions(executions);
  }),

  complete: protectedProcedure
    .input(
      z.object({
        executionId: z.number(),
        note: z.string().optional(),
        fileUrls: z.array(z.string()).optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const [execution] = await db
        .select()
        .from(workflowStepExecutions)
        .where(
          and(
            eq(workflowStepExecutions.id, input.executionId),
            eq(workflowStepExecutions.clubId, ctx.user.clubId!),
          ),
        )
        .limit(1);
      if (!execution) throw new TRPCError({ code: "NOT_FOUND" });
      if (ctx.user.role !== "admin" && execution.assigneeId !== ctx.user.id) {
        throw new TRPCError({ code: "FORBIDDEN" });
      }

      await db
        .update(workflowStepExecutions)
        .set({
          status: "completed",
          completedAt: new Date(),
          completedBy: ctx.user.id,
          note: input.note,
          fileUrls: input.fileUrls ? JSON.stringify(input.fileUrls) : undefined,
        })
        .where(eq(workflowStepExecutions.id, input.executionId));

      const [updated] = await db
        .select()
        .from(workflowStepExecutions)
        .where(eq(workflowStepExecutions.id, input.executionId))
        .limit(1);
      return updated;
    }),
});

async function enrichExecutions(executions: (typeof workflowStepExecutions.$inferSelect)[]) {
  const instanceIds = [...new Set(executions.map((e) => e.instanceId))];
  const stepIds = [...new Set(executions.map((e) => e.stepId))];

  const instances =
    instanceIds.length > 0
      ? await db.select().from(workflowInstances).where(inArray(workflowInstances.id, instanceIds))
      : [];
  const steps =
    stepIds.length > 0 ? await db.select().from(sopSteps).where(inArray(sopSteps.id, stepIds)) : [];
  const templateIds = [...new Set(instances.map((i) => i.templateId))];
  const templates =
    templateIds.length > 0
      ? await db.select().from(sopTemplates).where(inArray(sopTemplates.id, templateIds))
      : [];
  const matchIds = [...new Set(instances.map((i) => i.matchId))];
  const matchRows = matchIds.length > 0 ? await db.select().from(matches).where(inArray(matches.id, matchIds)) : [];

  return executions.map((execution) => {
    const instance = instances.find((i) => i.id === execution.instanceId) ?? null;
    const step = steps.find((s) => s.id === execution.stepId) ?? null;
    const template = instance ? templates.find((t) => t.id === instance.templateId) ?? null : null;
    const match = instance ? matchRows.find((m) => m.id === instance.matchId) ?? null : null;
    return { execution, step, template, match };
  });
}

export const workflowRouter = router({
  templates: templatesRouter,
  steps: stepsRouter,
  instances: instancesRouter,
  execute: executeRouter,
});
